### ISSUE TITLE
Multipoint Calibration Library Issue

### ISSUE THREAD

**Issue by rhosbach** [lab11/powerblade#12]
@nealjack It looks like line 16 of chroma63800.py should be `self.inst.write(':LOAD:MODE CURR')`, not `self.inst.write(':LOAD:MODE POW')`.

https://github.com/lab11/powerblade/blob/42c69cbebb2cbbde44f3fa67d518eb6a69de4123/data_collection/multipoint_calibration/chroma63800.py#L16

**Comment by nealjack** [comment]
You're right! I just hadn't tested setting the current.

Should be fixed in 0393291
