### ISSUE TITLE
Num Received Number Confusing?

### ISSUE THREAD

**Issue by bradjc** [lab11/powerblade#2]
With multiple powerblades, sometimes it prints 8, sometimes 0, which I believe are both incorrect (assuming it is a count of the repeated advertisements that powerblade sends). After a brief look, it seems like iden_count is a global value that will get incremented by multiple powerblades, leading to what I'm seeing.

**Comment by bradjc** [comment]
Also, "Packets in last 30s" doesn't seem quite right, and looking at the code it seems the maximum number of packets considered is capped at 30, even if there may have been more.

**Comment by sdebruin** [comment]
Yea both of those were hacky, put in place in a time of need. I think this and other analytics don’t belong in the shipping version of this code. All the shipping version should do is unpack the packet, calculate and apply the scaling values, and calculate PF.

**Comment by brghena** [comment]
Data access example script has been simplified as of edfb0dd76f5874c72035965f09f3644942e675af
