### ISSUE TITLE
How do you get PowerBlades

### ISSUE THREAD

**Issue by brghena** [lab11/powerblade#9]
@jovonni asked:

> How are you guys even able to work on this on your own? Can you purchase one?

Thanks for the interest. PowerBlade has been a very fun system to work with. We're graduate students in [Lab11](http://lab11.eecs.umich.edu/) and have been lucky to have the resources to pursue projects like these.

Unfortunately, we are not currently selling PowerBlades. However, all the hardware files are open source and available in this github repo. Theoretically, you could fabricate and assemble some yourself (or alternatively, take part of the design and include it in some other work inspired by PowerBlade). The PCB was designed in [Eagle](https://cadsoft.io/).

Hardware files (we are currently using rev 3_5): https://github.com/lab11/powerblade/tree/master/eagle/powerblade

**Comment by boogerlad** [comment]
Is powerblade still being worked on(rev 4)? I'd love to buy some.

**Comment by brghena** [comment]
Hey @boogerlad thanks for the interest. We are indeed still working on PowerBlade for research purposes. However, they're still nor for sale at this time. One of the issues we're addressing is how to redesign PowerBlade such that it passes UL certification and is safe for users. Until we figure out a solution for that, we aren't comfortable in selling them.
